### ISSUE TITLE
Problem with some style syntaxes in markdown

### ISSUE THREAD

**Issue by Rapougnac** [ItzDerock/discord-html-transcripts#1]
Hello, I've noticed that some syntaxes in markdown don't work, like the italic style made with an underscore instead of an asterisk, and the spoiler style
![](https://cdn.discordapp.com/attachments/903746731278237706/903747078948270150/ok_Mozilla_Firefox_29.10.2021_22_46_13.png)
There are problems with language support, an example in TypeScript:
![](https://cdn.discordapp.com/attachments/903746731278237706/903751330198351922/ok_Mozilla_Firefox_29.10.2021_23_04_25.png) But here I noticed that if I remove `nohighlight` from the class of the `div` element, the syntax appear.

The markdown hyperlinks doesn't show in html:
![](https://cdn.discordapp.com/attachments/903746731278237706/903747068563181588/ok_Mozilla_Firefox_29.10.2021_22_46_23.png)

I rewrotted a function for this:
```js
/**
 * Convert markdown hyperlinks to html hyperlinks
 * @param {string} text The text to convert to html `a` tag
 * @returns {string} The converted text
 * Base was found here: https://gist.github.com/alordiel/ed8587044be07e408f5f93b3124836b3
 */
function markdownHLToHtmlHL(text) {
  // Replace carriage return, line feed by classic line break in html
  text = text.replace(/(?:\r\n|\r|\n)/g, '<br />');

  // Check for links
  const elements = text.match(/\[.*?\)/g);
  // If no links, return base text
  if (elements.length === 0) return text;
  else {
    for (const element of elements) {
      // Get the content of the hyperlink
      const content = element.match(/\[(.*?)\]/)[1];
      // Get the link of the hyperlink
      const url = element.match(/\((.*?)\)/)[1];

      text = text.replace(
        element,
        `<a href="${url}" target="_blank">${content}</a>`
      );
    }
  }
  return text;
}
```
If I can make a suggestion, for the syntax styling, [this theme](https://gist.github.com/cherryblossom000/6c59a9a2436eaddbe4f388e3ae145e4a) of highlight.js is the same that discord uses.

I would have gladly made a pull request, unfortunately, it's beyond my capabilities 😓

**Comment by ItzDerock** [comment]
I completely forgot about underscore italics! 
Thanks for the report - I'll fix everything asap.

**Comment by ItzDerock** [comment]
This should all be fixed now.
I'll push all my changes in a second.

syntax highlighting and underscore italics: https://img.derock.dev/o5Mhpx.png
spoilers: https://img.derock.dev/ts9I0j.gif
inline links: https://img.derock.dev/jXxEH4.png
(can only be used by webhooks, or embed descriptions/fields since that's how discord does it)
