### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Justman10000** [ItzDerock/discord-html-transcripts#101]
Hi, i get the error:

> TypeError: Cannot read properties of undefined (reading 'path')

**Comment by Justman10000** [comment]
@ItzDerock

**Comment by ItzDerock** [comment]
Can you provide the full stack-trace and also some code?

**Comment by Justman10000** [comment]
> Can you provide the full stack-trace and also some code?

![grafik](https://user-images.githubusercontent.com/49990629/209175939-76882ede-7173-4d06-bde5-93f22ca3171b.png)

**Comment by Justman10000** [comment]
> Can you provide the full stack-trace and also some code?

> Can you provide the full stack-trace and also some code?

![grafik](https://user-images.githubusercontent.com/49990629/209175939-76882ede-7173-4d06-bde5-93f22ca3171b.png)

```js
const attachment = discordTranscripts.createTranscript(interaction.channel);

interaction.channel.send({
  files: [attachment],
});
```

**Comment by Justman10000** [comment]
> Can you provide the full stack-trace and also some code?

```js
const attachment = discordTranscripts.createTranscript(interaction.channel);

interaction.channel.send({
  files: [attachment],
});
```

![grafik](https://user-images.githubusercontent.com/49990629/209175939-76882ede-7173-4d06-bde5-93f22ca3171b.png)

**Comment by ItzDerock** [comment]
What version of discord.js are you using? (npm list discord.js)

**Comment by Justman10000** [comment]
> What version of discord.js are you using? (npm list discord.js)

![grafik](https://user-images.githubusercontent.com/49990629/209176817-62d6ec9e-2d93-48f4-8f34-5095519d0fd1.png)

**Comment by Justman10000** [comment]
As if the await makes that much difference

**Comment by ItzDerock** [comment]
createTranscripts(...) returns a Promise. I don't think discord.js accepts a promise inside of the `files` option.
Adding an `await` will resolve the promise before passing it to discord.js

**Comment by Justman10000** [comment]
Okay, thanks
