### ISSUE TITLE
New Discord font

### ISSUE THREAD

**Issue by thatkev** [ItzDerock/discord-html-transcripts#104]
With the release of Discord's new font (gg sans) at the beginning of this month, will we be seeing the font in the transcripts soon?
I found the `.woff2` font file in Discord's assets: https://cdn.discordapp.com/assets/stripe/ggsans-vf.woff2

**Comment by ItzDerock** [comment]
I don’t think you are allowed to use gg sans without permission. 
See the [2nd faq here](https://support.discord.com/hc/en-us/articles/9507780972951-gg-sans-Font-Update-FAQ)
