### ISSUE TITLE
Css issue with images 

### ISSUE THREAD

**Issue by CayeOficial** [ItzDerock/discord-html-transcripts#105]
Images that are sent on channels and cannot show on the transcript due to the channel being deleted, actually have a bigger size than it should be, which causes problems on mobile and pc.

Example transcript: https://transcripts.horusmc.net/WSSGW-67QDD-YGAO4-9GSK1-RSZLQ

**Comment by ItzDerock** [comment]
Fixed and released in [`3.1.3`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/v3.1.3)
