### ISSUE TITLE
Time Stamps on Transcripts show whenever the transcript is opened, not when it was actually sent by the client

### ISSUE THREAD

**Issue by Zer0Cool0** [ItzDerock/discord-html-transcripts#107]
When viewing a transcript after it has been saved, the timestamp it shows is the current date of viewing, not when the message was actually sent.

**Comment by Zer0Cool0** [comment]
@ItzDerock This transcript here was saved 01/18/2023 @ 9:10PM EST. No matter when you open it, it shows date of "today".

**Comment by ItzDerock** [comment]
Released in [`3.1.3`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/v3.1.3)
