### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isTextBased')

### ISSUE THREAD

**Issue by rico0610** [ItzDerock/discord-html-transcripts#108]
This shows when I create a ticket as non-admin or owner and tries to close it. Admin or owner account will get this error as well when closing out the ticket create by non-admin or owner account.

**Comment by Zer0Cool0** [comment]
I don't think this is an issue with the transcripts. Can you show us the entire error?

**Comment by rico0610** [comment]
My bad. This is all good now. I've figured, I'm not getting the channel object correctly.
