### ISSUE TITLE
Default emojis returning a 404 image

### ISSUE THREAD

**Issue by balonsom** [ItzDerock/discord-html-transcripts#113]
The src of the images for default emojis like `:heart:` are returning a 404 error.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/4379580/217245413-40d6f55f-1e76-4428-8e21-5d589c3eb5fb.png">

As far as I've seen, the CDN is working fine but instead of using URL of code points `https://twemoji.maxcdn.com/v/latest/svg/2764-fe0f.svg` it works if only the first filename part is sent `https://twemoji.maxcdn.com/v/latest/svg/2764.svg`.

Maybe **twemoji** libary docs have more info about this.

**Comment by ItzDerock** [comment]
Will look into this. 
https://github.com/ItzDerock/discord-html-transcripts/blob/master/src/utils/utils.ts#L17
Issue probably originates from this function.

**Comment by ItzDerock** [comment]
able to reproduce, looking into how I can fix this.

**Comment by ItzDerock** [comment]
Looked into this a bit. I think all I need to do is implement the [grabTheRightIcon(...)](https://github.com/twitter/twemoji/blob/d94f4cf793e6d5ca592aa00f58a88f6a4229ad43/scripts/build.js#L344) function from twemoji into discord-html-transcripts

**Comment by ItzDerock** [comment]
Issue should be fixed with that commit. Note that emojis released in Unicode/Emoji 15 still will not work as some of the people on the team to release that were [laid off](https://github.com/twitter/twemoji/issues/570).

**Comment by ItzDerock** [comment]
released in 3.1.4
