### ISSUE TITLE
Problem with the videos.

### ISSUE THREAD

**Issue by GardoTL** [ItzDerock/discord-html-transcripts#114]
When I export a channel, the videos are not clickable. There are only thumbnails and it is impossible to click on the video to play it.

**Comment by ItzDerock** [comment]
I'm able to reproduce this, will fix soon. 
As a temporary workaround, you can right click and hit the show video controls button.

**Comment by GardoTL** [comment]
Hey, do you have any news? I tried to fix the problem on my side to help you but I didn't succeed :(

**Comment by ItzDerock** [comment]
should be fixed, released an update to @derockdev/discord-components. Nothing needs to be done on your end, all old transcripts should also be fixed too. May take a day for cache to expire though.
