### ISSUE TITLE
saveImages not storing raw image data

### ISSUE THREAD

**Issue by braxtongpoll** [ItzDerock/discord-html-transcripts#121]
Using the saveImages option is still using the discord.com URL for the image thus eventually being deleted.
My usage:
```js
     const attachment = await discordTranscripts.createTranscript(interaction.channel, {
                    saveImages: true,
                    footerText: `Copyright ${interaction.guild.name} ${new Date().getFullYear()}`,
                    poweredBy: false
                });
```

**Comment by ItzDerock** [comment]
Unable to reproduce this bug:
![image](https://user-images.githubusercontent.com/14848722/224513956-7f7e1610-cc7c-423c-b027-730a0e33fa19.png)
![image](https://user-images.githubusercontent.com/14848722/224513973-96702338-48e8-4d19-beda-0d55e2b8a1ad.png)

**Comment by braxtongpoll** [comment]
After trying it again it worked, sorry to bother 😓
