### ISSUE TITLE
Change hour 00:00 PM to 12:00 PM

### ISSUE THREAD

**Issue by LMS5413** [ItzDerock/discord-html-transcripts#142]
I would like to request a change in the time format used in the project. Currently, we are using the format 00:00 PM to represent noon, which can lead to confusion and misunderstandings among team members.

To avoid potential incorrect interpretations, I suggest adopting the format 12:00 PM to represent noon. This change will provide additional clarity, avoiding ambiguities and facilitating mutual understanding.

**Comment by VedshreeB** [comment]
Hey! I love to solve these kind of problems and have done them in javascript. I think I can figure it out. I request you to assign this to me.

**Comment by SerenModz21** [comment]
The provided issue resolves around [Date#toLocaleDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), which is used within the discord-components package ([source](https://github.com/ItzDerock/discord-components/blob/main/packages/core/src/util.ts#L11)). To get around this, regex replacement could be used.

For example, if you want "12:__ am" and "12:__ pm":
```js
"10/08/2023 00:21 pm".replace(/00:(\d{2})/, "12:$1")
// outputs: '10/08/2023 12:21 pm'

"10/08/2023 00:21 am".replace(/00:(\d{2})/, "12:$1")
// outputs: '10/08/2023 12:21 am'
```

This is not needed for the 24 hour click, so the ideal approach would be to condition this replacement for when the 12 hour clock is being used. As such, the following code below could be considered the solution.
```js
const date = new Date(value)
    .toLocaleDateString(undefined, {
        year: 'numeric',
	month: '2-digit',
	day: '2-digit',
	hour: '2-digit',
	minute: '2-digit',
	hour12: !hour24
    })
    .replace(',', '');

return hour24 ? date : date.replace(/00:(\d{2})/, '12:$1');
```
