### ISSUE TITLE
Issue with username showed

### ISSUE THREAD

**Issue by Ichinistes14** [ItzDerock/discord-html-transcripts#148]
![Capture d’écran 2023-08-11 163948](https://github.com/ItzDerock/discord-html-transcripts/assets/141771041/e0abe9df-f2d6-4826-9f0f-fc0bc52ee34b)
As we can see on the image, all names are replaced with "User" for real account and for bots at the creation of the file, I don't know where it can from but it happen to all transcript I do.

**Comment by ItzDerock** [comment]
Update discord.js to the latest version

**Comment by Ichinistes14** [comment]
Okay, I updated to the latest version (14.12.1) and now it's working.
I was in 14.11.0 before.
