### ISSUE TITLE
attachment appears above embed post 

### ISSUE THREAD

**Issue by gitagogaming** [ItzDerock/discord-html-transcripts#165]
I am having an issue here the attachment is appearing above the embed instead of within it.. trying to figrue out what may be causing this or how to resolve it. 

![image](https://github.com/ItzDerock/discord-html-transcripts/assets/76603653/da049591-748f-4c9e-a441-ba95dca5a071)

```          const embed = new EmbedBuilder()
          .setColor('#0099ff')
          .setTitle(`Ticket from ${interaction.user.username}`)
          .setDescription(`Ticket type: ${data.Ticket}`)
          .addFields(
            {name: 'Email:', value: emailInput, inline: true},
            {name: '** **', value: "** **", inline: true},
            {name: 'Username:', value: usernameInput, inline: true},
            )
          .addFields({name: 'Reason:', value: reasonInput, inline: true})
          .setFooter({text: `Ticket Closed by: ${i.user.username} @ ${new Date().toLocaleString()}`})

          // Send the file and the embed to the custom channel
          await archiveChannel.send({
            embeds: [embed],
            files: [attachment],
          });
          ```

**Comment by xCraimax** [comment]
If i recall it correctly, you can't put an attachement IN the Embed.

**Comment by SerenModz21** [comment]
> If i recall it correctly, you can't put an attachement IN the Embed.

You are correct. Only images can be shown inside embeds, with the exception of link embeds, which also allow videos.

**Comment by SerenModz21** [comment]
Unfortunately @gitagogaming, there is no way around this limitation. Reason being, that is just how Discord made it.

**Comment by TGTGamer** [comment]
@gitagogaming if it was a significant issue for you, send two separate messages. 

One to include the ticket data and a second one simply for the attachment.

**Comment by ItzDerock** [comment]
This issue is not related to discord-html-transcripts as we have no way to control where the attachment shows.
