### ISSUE TITLE
Define Maximum Output File Size for Discord HTML Transcripts

### ISSUE THREAD

**Issue by FabienBounoir** [ItzDerock/discord-html-transcripts#166]
Hello,

I've been using the "discord-html-transcripts" package and I'm pleased with its performance. However, I have a suggestion for improvement.

Feature Request:
Integrate a functionality to define the maximum size of the output file when creating a transcript with the base64 conversion of images. This would ensure that if the total size of the images exceeds the defined limit, subsequent images will not be converted. This feature would be beneficial for resource management when sending the transcript via a Discord bot to a channel.

Rationale:
By having the ability to set a maximum file size, users can optimize resource utilization and avoid concerns about file size when sharing transcripts through Discord channels. This enhancement would contribute to better overall performance and efficiency.

Thank you for considering this suggestion.

Best regards,
Bouns

**Comment by ItzDerock** [comment]
I will probably add some sort of callback for saving images so users can create their own functions to add new limitations or other features (see my response in #128).

Along with that, I'll have some sort of builder for the basic limitations, so expect an api like:
```js
createTranscript(channel, {
    callbacks: {
        resolveImageSrc: new TranscriptImageDownloader()
            .withMaxSize(5_000_000) /* 5mb in bytes */
            .withCompression() /* package will recompress the image */
            .build()
    }
});
```
