### ISSUE TITLE
Firefox not supported

### ISSUE THREAD

**Issue by NotDemonix** [ItzDerock/discord-html-transcripts#175]
![IMG_20240612_162934](https://github.com/ItzDerock/discord-html-transcripts/assets/90858555/ddcc8e4b-895c-4ed1-a943-e9bf7745f664)
Hey, looks like the transcripts don't load properly on Firefox.
![IMG_20240612_162946](https://github.com/ItzDerock/discord-html-transcripts/assets/90858555/c2fa1669-10dc-4271-9d19-2144ec5360c0)

**Comment by ItzDerock** [comment]
Unable to reproduce, can you provide more details? 
![image](https://github.com/ItzDerock/discord-html-transcripts/assets/14848722/5724a987-ec3e-4a1b-b0fa-78ca681839e2)

left = firefox, right = chrome-based browser

**Comment by NotDemonix** [comment]
This is the transcript the user sent with the bug
https://tickety.top/transcripts?id=24873z4z6j7x

**Comment by NotDemonix** [comment]
We are still running on the older release before you made the last change with react components

**Comment by ItzDerock** [comment]
still unable to reproduce:
![image](https://github.com/ItzDerock/discord-html-transcripts/assets/14848722/2b8d8a90-df25-4b37-812a-09b6114d0a0a)

**Comment by NotDemonix** [comment]
> still unable to reproduce: ![image](https://private-user-images.githubusercontent.com/14848722/340335150-2b8d8a90-df25-4b37-812a-09b6114d0a0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzUxMzksIm5iZiI6MTcxODYzNDgzOSwicGF0aCI6Ii8xNDg0ODcyMi8zNDAzMzUxNTAtMmI4ZDhhOTAtZGYyNS00YjM3LTgxMmEtMDliNjExNGQwYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE0MzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOTdmY2MwYjI0OGI1NzQxMTIyYTg0MjNkYTE5MzAwOThkMDU4OTczMWE0ZGQyZjgyYTk5OTIyNzgxMDQxMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hRiZy38DUAgHE7-fJ8JeAMTRu_PGpM9QpZv50gYSbLU)

Hm maybe it was some extension then or something with the user settings
