### ISSUE TITLE
Message content not showing

### ISSUE THREAD

**Issue by Ichinistes14** [ItzDerock/discord-html-transcripts#178]
Hello,

When I transcript a channel, on the html I see everything but not the content of message only (see picture)

![image](https://github.com/user-attachments/assets/fcb23d07-1393-457d-8eb7-87bb1e2ccf1a)

Here is my code (I use Typescript) :

`const member = interaction.member as GuildMember;
        const ticketChannel = interaction.channel as TextChannel;
        const roles = [
          this.client.config.staffId,
          this.client.config.testStaffId,
        ];
        const hasRole = member.roles.cache.some((r) => roles.includes(r.id));

        if (!hasRole) {
          return await interaction.reply({
            content: "Vous n'avez pas le droit de fermer ce ticket.",
            ephemeral: true,
          });
        }

        await createTranscript(ticketChannel).then(
          async (r) => {
            await (
              interaction.guild?.channels.cache.get(
                this.client.config.transcriptLogs
              ) as TextChannel
            ).send({
              embeds: [
                new EmbedBuilder()
                  .setColor("Aqua")
                  .setTitle("Fermeture Ticket")
                  .setDescription(`Fermé par : ${member.user}\n`)
                  .setTimestamp(),
              ],
              files: [r],
            });
            ticketChannel.delete().catch((error) => console.error(error));
          }
        );`

I got no error in my console and use discord@14.15.3

**Comment by RazorMeister** [comment]
Hi, I've got the same problem as the OP and there is no comment about that issue. @Ichinistes14 could you help with that?

Discord js version: 14.16.2
discord-html-transcripts version: 3.2.0

**Comment by Ichinistes14** [comment]
Hi,

Like you say, don’t forget the intents and partials for it to work.
I figured that after modifying the plugin and see it wasn’t getting the message content but all the rest.

![IMG_1702](https://github.com/user-attachments/assets/ba18d72e-8c27-4d6d-9135-adf098e94da7)
