### ISSUE TITLE
Add URL property to can get the URL of the transcript

### ISSUE THREAD

**Issue by PabloRNC** [ItzDerock/discord-html-transcripts#21]
I like to get the URL of the transcript but i cannot because the property URL of Discord Attachments doesn't work and give me undefined so can you add this property and so if this is posible how can i do? 
Thanks

**Comment by ItzDerock** [comment]
What URL do you expect to be there?
The package doesn't upload the transcript to a server, so there's no public URL.

If you want the discord cdn url, you'll have to send it, then get it from the sent message's attachments.
