### ISSUE TITLE
can you add Reactions feature ?

### ISSUE THREAD

**Issue by AhmedMondo** [ItzDerock/discord-html-transcripts#32]
So it tracks reactions on messages with its counter

**Comment by ItzDerock** [comment]
implemented, will release as soon as the last open issue is resolved.
example output:
![image](https://user-images.githubusercontent.com/14848722/171769016-59e6efcc-329d-4d2b-b82a-2e8c234de1c7.png)

**Comment by ItzDerock** [comment]
Released in [`2.5.6`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/2.5.6)
