### ISSUE TITLE
Mentioned roles not showing correctly

### ISSUE THREAD

**Issue by AhmedMondo** [ItzDerock/discord-html-transcripts#33]
Role mention is bugged 

Its appears like that <@&1234567891234567> instead of `@Role's name`

**Comment by ItzDerock** [comment]
added, will release soon;
![image](https://user-images.githubusercontent.com/14848722/171762029-508879b5-1840-4f5c-b74c-8a0d05e46897.png)

**Comment by ItzDerock** [comment]
Released in [`2.5.6`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/2.5.6)

**Comment by ItzDerock** [comment]
Released in [`2.5.6`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/2.5.6)
