### ISSUE TITLE
[Suggestion] Add support for Interactions

### ISSUE THREAD

**Issue by wechselgeld** [ItzDerock/discord-html-transcripts#36]
Would it be possible to add support for buttons (and/or select menus)?

**Comment by HazimAr** [comment]
I can try to take a look @ItzDerock as I've got some free time

**Comment by ItzDerock** [comment]
> I can try to take a look @ItzDerock as I've got some free time

sure go ahead! make a draft pr and I may help out a bit if I get time.

**Comment by PlutodyneSpaceIndustries** [comment]
This is actually already possible. You just need to Catch the button interaction and assign the Transcript function to it.

**Comment by ItzDerock** [comment]
will be implemented in [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3)

**Comment by ItzDerock** [comment]
added example: 
![image](https://user-images.githubusercontent.com/14848722/192111587-fe858037-67ab-4166-8287-018146b93650.png)

will send another message when this gets released

**Comment by ItzDerock** [comment]
released
