### ISSUE TITLE
Template Question & Attachment Issue

### ISSUE THREAD

**Issue by WolfTM** [ItzDerock/discord-html-transcripts#38]
Hey,

So at first is it possible to change the html theme/template?
I would like to improve it and customize it.

Second I'm experiencing a little problem with attachments.
https://prnt.sc/FnpjdIlzOYr9
And the url that it goes to
https://prnt.sc/JMMAbJudUmDh

Not sure what the issue is here. Or why it is acting up like this.

-Wolf

**Comment by ItzDerock** [comment]
Can you show the full error shown in the 2nd image?
Also make sure you are running the latest version of discord.js

**Comment by WolfTM** [comment]
Yes,
This is the error
https://prnt.sc/yysDeSWhesYf

**Comment by ItzDerock** [comment]
the original message/image was deleted, therefore, discord deleted it from their servers. 
if you need the images saved with the transcript, check out the `saveImages` option.

**Comment by WolfTM** [comment]
Ah alright. Thanks. I totally forgot you had options, my bad.
