### ISSUE TITLE
Embed Formatting Block Quotes

### ISSUE THREAD

**Issue by WolfTM** [ItzDerock/discord-html-transcripts#39]
Hey,

Not sure if it is intentional.
But embeds seem to not be formatted with the Block Quotes formatting.
https://prnt.sc/kIdaQ9PEq9ga

-Wolf

**Comment by ItzDerock** [comment]
I don't believe I ever added support for quotes.
Will implement when I get the time

**Comment by WolfTM** [comment]
Alright sounds good. 👍

**Comment by ItzDerock** [comment]
will be implemented in [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3)

**Comment by ItzDerock** [comment]
added in next release
![image](https://user-images.githubusercontent.com/14848722/192111664-e40ded61-9f03-4a14-a6b2-def5df17a606.png)

**Comment by ItzDerock** [comment]
released!
