### ISSUE TITLE
V14 Bug

### ISSUE THREAD

**Issue by ChirujanoCodding** [ItzDerock/discord-html-transcripts#40]
i programming a bot in TS and when i use the function `createTranscript` the command fails, i checked yet if the channel is TextChannel but doesn't work.

**Comment by ItzDerock** [comment]
can you send the error?

**Comment by ChirujanoCodding** [comment]
image of the code:
![image](https://user-images.githubusercontent.com/84428770/173901233-fd48bd29-16f4-4abe-ad11-4e1b001f2611.png)
```typescript
                    if (interaction.channel?.isTextBased()) {
                        const file = await createTranscript(interaction.channel, {
                            limit: -1, returnType: "attachment", fileName: "transcript.html", minify: true, saveImages: false, useCDN: false
                        });
                        await interaction.reply({ content: "`✔️` Transcript created!", files: [file] })
                    }
                    break;
```
image of the error:
![image](https://user-images.githubusercontent.com/84428770/173901488-8134d2fb-c349-446a-873f-06db5716ef9e.png)

**Comment by ItzDerock** [comment]
Found the cause, in @dev, they changed from `.isText()` to `isTextBased()`
Will push an fix shortly.

**Comment by ChirujanoCodding** [comment]
Thanks!

**Comment by ChirujanoCodding** [comment]
hi, i found a new bug.
same code but different error now.
![image](https://user-images.githubusercontent.com/84428770/174833854-9bf646d9-0e2b-4bd7-86a0-72979dc76ea3.png)
