### ISSUE TITLE
Function error

### ISSUE THREAD

**Issue by SamDoesDev** [ItzDerock/discord-html-transcripts#41]
It seems when doing the command it returns an error `TypeError: inputChannel.isThread is not a function`, I'm unsure on what this error specifies or means. 
![image](https://user-images.githubusercontent.com/101457418/173896548-a6e9062e-f8d0-43af-91f6-57065d1f43aa.png)

**Comment by ItzDerock** [comment]
This is because you are running v12.
I can fix this, but I can't guarantee that the rest of the package will work and will continue to work in the future, as it's not really feasible to support v12, v13 and v14.

**Comment by SamDoesDev** [comment]
Would you be able to add seperate versions for the package?
