### ISSUE TITLE
Suggestion & bug report

### ISSUE THREAD

**Issue by XenKys** [ItzDerock/discord-html-transcripts#42]
Hello! I would like to recommend that you add buttons to the transcripts as well! And I noticed that when a user sends a link it doesn't appear blue like on Discord...

**Comment by ItzDerock** [comment]
will be implemented in [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3)

**Comment by ItzDerock** [comment]
added in next release: 
![image](https://user-images.githubusercontent.com/14848722/192111645-902a86fb-68eb-47d3-93dc-f2aee8adc2d2.png)

**Comment by ItzDerock** [comment]
released!
