### ISSUE TITLE
New bug founded in V14

### ISSUE THREAD

**Issue by ChirujanoCodding** [ItzDerock/discord-html-transcripts#44]
i wrote a issue a week ago about a bug in v14, i use the same code for the new version (2.5.8) and a new error appears.
![image](https://user-images.githubusercontent.com/84428770/174836590-19709c73-6129-44ad-9b86-1a5d9a3fdf90.png)

![image](https://user-images.githubusercontent.com/84428770/174836532-a73b2e9b-693b-4415-b3cd-379ddcb2099c.png)

**Comment by Tymonsky** [comment]
same
