### ISSUE TITLE
Feature Request - Upload / Save

### ISSUE THREAD

**Issue by WolfTM** [ItzDerock/discord-html-transcripts#46]
Upload / Save

An option to either save a transcript locally or upload it to a webserver & get url to send to user/staff rather then a html file.

**Comment by ItzDerock** [comment]
For saving locally, this can already be done with `returnType` set to `buffer`  and by using fs.writeFileSync
For uploading to a webserver, there is no way for the package to know how to communicate with your webserver.

And for those reasons, these features will not be added to the package.
