### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flavioope** [ItzDerock/discord-html-transcripts#47]
Hello, I have had this problem for a long time and I have not been able to solve it, does anyone know how I can solve this error?

![image](https://user-images.githubusercontent.com/91861737/177055514-b986a7f3-69f8-4afd-9090-5ec877a9ca66.png)

**Comment by ItzDerock** [comment]
This happens if the image gets deleted off of discord (due to message deleted or channel deleted)

You can enable the `saveImages` option to have the package download all the images and save them in the html file, but this may increase filesize and may hit the Discord upload limit quicker.
