### ISSUE TITLE
[Bug] Message containing a link causes the entire message to become a link

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [ItzDerock/discord-html-transcripts#51]
If a message contains a link, it causes the entire message to become a hyperlink. 

<img width="956" alt="Screenshot 2022-07-25 at 18 46 45" src="https://user-images.githubusercontent.com/30740511/180841689-6d415d49-5451-4069-a433-761c3f87b8a8.png">

**Comment by ItzDerock** [comment]
kind-of fix implemented, in the case you provided it'll just ignore the link and not hyperlink it.
I need to refactor how content gets formatted as there are a lot of edge cases where the current function will incorrectly format the content.
