### ISSUE TITLE
Save images not actually saving images

### ISSUE THREAD

**Issue by flavioope** [ItzDerock/discord-html-transcripts#52]
Hi, I don't know if this is a suggestion, but could you please add an option so that this doesn't happen?

![image](https://user-images.githubusercontent.com/91861737/181416514-51477a9f-5843-4c9d-8e04-469e7926a92a.png)

Or could it be fixed if when the user does not see the channel, the image is still saved, I do not know if it is possible, please. :( Because when I use, for example, /close on my server, that always happens to me.

**Comment by ImMaxUK** [comment]
> Hi, I don't know if this is a suggestion, but could you please add an option so that this doesn't happen?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/91861737/181416514-51477a9f-5843-4c9d-8e04-469e7926a92a.png)
> 
> 
> 
> Or could it be fixed if when the user does not see the channel, the image is still saved, I do not know if it is possible, please. :( Because when I use, for example, /close on my server, that always happens to me.
> 
> 

A solution to this already exists.
You can use saveImages.

**Comment by flavioope** [comment]
> > Hi, I don't know if this is a suggestion, but could you please add an option so that this doesn't happen?
> > ![image](https://user-images.githubusercontent.com/91861737/181416514-51477a9f-5843-4c9d-8e04-469e7926a92a.png)
> > Or could it be fixed if when the user does not see the channel, the image is still saved, I do not know if it is possible, please. :( Because when I use, for example, /close on my server, that always happens to me.
> 
> A solution to this already exists. You can set saveImages to true.

![image](https://user-images.githubusercontent.com/91861737/181651924-03fafc13-384c-4292-8fca-39a3be1fd55f.png)

**Comment by ItzDerock** [comment]
Can you send that transcript over so I can take a look? If not, can you open inspect and show me the image src for that image?

**Comment by flavioope** [comment]
Where can I send you the transcript? Here it won't let me send it

**Comment by ItzDerock** [comment]
anywhere, google drive, dropbox, discord and then copy the url, etc

**Comment by ItzDerock** [comment]
I should probably also add, can you verify you are running the latest version?

**Comment by flavioope** [comment]
> I should probably also add, can you verify you are running the latest version?

Although I have outdated the resource now I will update it anyway here I leave the transcript for you to check
https://discord.com/channels/@me/912546804283867136/1002361539883454574

**Comment by ItzDerock** [comment]
> https://discord.com/channels/@me/912546804283867136/1002361539883454574

I meant the download link, not the message link - sorry for not clarifying. 
https://img.derock.dev/XffieN.png

FYI, someone reported a bug in the discord today -- the latest version, while it does actually save the images, it'll move all the images to the bottom of the transcript.

**Comment by flavioope** [comment]
> 

https://cdn.discordapp.com/attachments/980900838258147338/1002059664273453126/transcript-es-verficar-guayabita.html

**Comment by flavioope** [comment]
Update the resource and it seems that the images are now saved but do you know how I can do if the file weighs more than what discord allows, it can still be sent or not?

**Comment by Krayon0** [comment]
Is this not because the channel the images were in has been deleted so discord deletes them from their servers as well?

**Comment by ItzDerock** [comment]
> Is this not because the channel the images were in has been deleted so discord deletes them from their servers as well?

yes, which is why the package will attempt to save the images locally in the file if the `saveImages` option is true, but there's a bug with that (#53)
