### ISSUE TITLE
saveImages: true puts images at the bottom of the transcript.

### ISSUE THREAD

**Issue by Zer0Cool0** [ItzDerock/discord-html-transcripts#53]
When using the `saveImages: true` "setting", the images get saved to the bottom of the transcript regardless of when they were sent.

(Copied your response from the discord.)

> issue comes from the fact that fetching an image takes time, and the package doesnt handle that properly
it adds the message as soon as it gets processed. For any normal message this will take the same amount of time for each message; and therefore will follow the order of the input
but images add a ton of processing time since you need to download the image
so all the nromal messages finish processing and get appended
the image though doesnt get appended until later since thats when it finishes downloading

**Comment by AutoKill** [comment]
I'm also having this issue.

**Comment by Zer0Cool0** [comment]
> I'm also having this issue.

This is a confirmed issue by the maintainer.

**Comment by ItzDerock** [comment]
will send a message here once this gets released

**Comment by ItzDerock** [comment]
released
