### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Shelly7w7** [ItzDerock/discord-html-transcripts#54]
Currently couple of vital things are missing and I would love to see these being implemented!

- Quotes and Block Quotes
- Rendering of custom emojis in embed titles

**Comment by ItzDerock** [comment]
> Quotes and Block Quotes
duplicate of #39 

> Rendering of custom emojis in embed titles
this should be doable -- will implement when I get the time.

**Comment by ItzDerock** [comment]
will be implemented in [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3)

**Comment by ItzDerock** [comment]
released!
