### ISSUE TITLE
Message fetch limites (in-complete HTML)

### ISSUE THREAD

**Issue by Itz-Hyperz** [ItzDerock/discord-html-transcripts#57]
When archiving a channel it doesn't fetch all the messages, it maxes out at 100 messages per channel.

**Comment by Itz-Hyperz** [comment]
*Reference: https://stackoverflow.com/questions/55153125/fetch-more-than-100-messages*

**Comment by Itz-Hyperz** [comment]
Resolves:
- #56
- #44 
- #37 
- #35

**Comment by ItzDerock** [comment]
already implemented in [src/index.ts](https://github.com/ItzDerock/discord-html-transcripts/blob/04a38efb561a5efd2d45ddbc152850c87357bf95/src/index.ts#L97)

**Comment by Itz-Hyperz** [comment]
It still seems to happen for me though.

**Comment by Krayon0** [comment]
Had this same issue today so fixed it with this
[Pull Request](https://github.com/ItzDerock/discord-html-transcripts/pull/58)

**Comment by ItzDerock** [comment]
re-open if issue still exists
