### ISSUE TITLE
html format error

### ISSUE THREAD

**Issue by cyb3rgh05t** [ItzDerock/discord-html-transcripts#62]
### Discussed in https://github.com/ItzDerock/discord-html-transcripts/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **cyb3rgh05t** August 14, 2022</sup>
Hi,

i have a little issue that i am not able te resolve, maybe you can help me?

Testing my bot over Visual Studio Code, transcript attachement show up like this:
![image](https://user-images.githubusercontent.com/5200101/184549076-01e09a82-50d2-48e0-86eb-afda6527f6c7.png)
this is the correct format.

but if i dockerize my bot, the transcript attachement show up like this:
![image](https://user-images.githubusercontent.com/5200101/184549117-f832be51-750e-44a5-a87a-5e9a0cfa91d1.png)

do you know what i can do to fix the format?

Thanks
</div>

**Comment by ItzDerock** [comment]
Are you able to send your dockerfile so I can take a look at this?

**Comment by JRTMediaUK** [comment]
I am having the same issue but without Docker.

**Comment by ItzDerock** [comment]
Are you running this on windows or linux?
And does the resulting HTML still display properly in the browser?

**Comment by JRTMediaUK** [comment]
> Are you running this on windows or linux? And does the resulting HTML still display properly in the browser?

I am running the discord bot on Linux. The HTML does still display ok, it's just invalid HTML5 due to that DOCTYPE tag which is causing discord to show the formating incorrectly when sent as an attachment

**Comment by ItzDerock** [comment]
Hm, ok, so seems like maybe this is an issue with jsdom + linux (discord-html-transcript isn't platform dependent)
Will look into this.

**Comment by cyb3rgh05t** [comment]
> Are you able to send your dockerfile so I can take a look at this? the issue is probably coming from jsdom.

yes for sure, thanks for looking into this. i am using ubuntu 16.04 with docker.

```
FROM node:16.16.0

LABEL maintainer=cyb3rgh05t
LABEL org.opencontainers.image.source https://github.com/cyb3rgh05t/mr.streamnet


RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot

COPY package.json /usr/src/bot

RUN apt-get update && apt-get install -qq build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev g++ software-properties-common 
RUN npm install

COPY . /usr/src/bot

CMD ["node", "."]
```

**Comment by ItzDerock** [comment]
this will be fixed in the [v3](https://github.com/ItzDerock/discord-html-transcripts/tree/v3) rewrite

**Comment by ItzDerock** [comment]
re-open if this issue still occurs in the new v3 update.

**Comment by cyb3rgh05t** [comment]
thanks :) no way to fix this also for discord js v13?
