### ISSUE TITLE
text wont show

### ISSUE THREAD

**Issue by devtyp** [ItzDerock/discord-html-transcripts#63]
for some reason, the text of a channel will not show
@ItzDerock 

![image](https://user-images.githubusercontent.com/110949861/184794094-8b119908-1906-40aa-a5a0-5895184d773e.png)

**Comment by ItzDerock** [comment]
Strange, are you running the latest release?

**Comment by devtyp** [comment]
Yes, 
![image](https://user-images.githubusercontent.com/110949861/184915114-620aa594-76d2-415d-8088-05f4e90095f2.png)

**Comment by ItzDerock** [comment]
Do you have the message content intent enabled in your client and on the developer portal.

**Comment by devtyp** [comment]
i just enabled it on the developer portal and now it works.. hah

**Comment by devtyp** [comment]
thanks!
