### ISSUE TITLE
Embed Mentions

### ISSUE THREAD

**Issue by Johannes7k75** [ItzDerock/discord-html-transcripts#8]
Hi i noticed that you package dont format mentions in embeds.
Do you have a intention do add that?

**Comment by ItzDerock** [comment]
I actually don't think I ever implemented formatting mentions, I'll add it if I have time, or if you or someone else is able to, make a PR.

**Comment by HazimAr** [comment]
> Hi i noticed that you package dont format mentions in embeds. Do you have a intention do add that?

I will be probably fixing that and other few things on my fork of this
https://github.com/HazimAr/Discord-Transcripts

**Comment by ItzDerock** [comment]
I have added mention formatting!
This relies on you having the mentioned channel/user cached - since making a fetch for each mentioned user is not a great idea.

![example](https://img.derock.dev/zCfvcr.png)
