### ISSUE TITLE
Fetching Messages

### ISSUE THREAD

**Issue by AhmedMondo** [ItzDerock/discord-html-transcripts#81]
fetching system fetch only 100 messages even if i put limit: -1 or remove it it still fetch only 100 messages and not all channel's messages
idk why 

![image](https://user-images.githubusercontent.com/55901601/194671977-5908a3ed-295d-4fef-adc5-c01db8e7d861.png)

**Comment by AhmedMondo** [comment]
should i pass my own fetching system or there is another solution ?

**Comment by AhmedMondo** [comment]
and is there any plans to support stickers ?

**Comment by AhmedMondo** [comment]
Here is the function i made for fetching the whole messages and it works

```
async function fetchAllMessages(channel, limit = Infinity) {
  if (!channel) {
    throw new Error(`Expected channel, got ${typeof channel}.`);
  }
  if (limit <= 100) {
    return channel.messages.fetch({ limit });
  }

const { Collection } = require('discord.js');
  let collection = new Collection();
  let lastId = null;
  let options = {};
  let remaining = limit;

  while (remaining > 0) {
    options.limit = remaining > 100 ? 100 : remaining;
    remaining = remaining > 100 ? remaining - 100 : 0;

    if (lastId) {
      options.before = lastId;
    }

    let messages = await channel.messages.fetch(options);

    if (!messages.last()) {
      break;
    }

    collection = collection.concat(messages);
    lastId = messages.last().id;
  }
  return collection.reverse()
}

```

**Comment by ItzDerock** [comment]
> and is there any plans to support stickers ?
Can you create a separate issue for this? If it's possible I will implement it.

**Comment by AhmedMondo** [comment]
> > and is there any plans to support stickers ?
> 
> Can you create a separate issue for this? If it's possible I will implement it. 

Ok
