### ISSUE TITLE
Support Markdown?

### ISSUE THREAD

**Issue by WolfTM** [ItzDerock/discord-html-transcripts#83]
Hey,

I noticed mark down is not being displayed, I guess it's not supported?
If so is this possible?
https://prnt.sc/2U7U8POUpH-5

**Comment by ItzDerock** [comment]
thats strange, it should display there...
Can you verify you've enabled message content intent, and if possible can you send the broken transcript file?

**Comment by WolfTM** [comment]
Yest it is enabled.
Can it be causing the issue because we use Ansi Markdown?
Because the browser console says it is an unknown language.
https://prnt.sc/oPfYZo0bFEkT

Here is the file, (WeTransfer)
https://we.tl/t-BonOie3HT2

**Comment by ItzDerock** [comment]
Forgot to mention, but this was fixed in the last release.
