### ISSUE TITLE
[Bug] Sending weird jpg file.

### ISSUE THREAD

**Issue by japandotorg** [ItzDerock/discord-html-transcripts#85]
No idea why but the library has been working perfectly fine for me, but after I tried to shift from manual button interaction transcripts to more like a automatic transcript thingy, the filename/file is showing up as a jpg even tho i've explicitly set it to save it as `transcript.html` within the code.
![image](http://i.melonbot.io/978.png)
![image](http://i.melonbot.io/969.png)

**Comment by ItzDerock** [comment]
I'm unable to reproduce this bug.

Can you try setting returnType to `"buffer"` and create your own attachment object?
```js
const attachment = new AttachmentBuilder(transcriptBuffer, {
    name: "transcript.html"
});
```
and see if that fixes the issue.

**Comment by ItzDerock** [comment]
re-open if still an issue
