### ISSUE TITLE
Custom filenames won't work

### ISSUE THREAD

**Issue by CaptSpider4** [ItzDerock/discord-html-transcripts#86]
```js
const attachment = await discordTranscripts.createTranscript(interaction.channel, {
        limit: -1,
        returnType: 'attachment',
        fileName: `${ticketData.TicketID}-transcript-${ticketUser.user.tag}.html`,
        poweredBy: true
});
```
Even though after adding like this its generating filename as default i.e `trascript-(channel_id)`

**Comment by CaptSpider4** [comment]
It was working in the previous version but in the new update its not

**Comment by imranbarbhuiya** [comment]
use `filename`

**Comment by CaptSpider4** [comment]
Ohh it was `fileName` in 2.0 so i didn't change that one. Should have noticed they changed it to `filename`. Thanks for the help
