### ISSUE TITLE
[Feature request] Pinned message icon

### ISSUE THREAD

**Issue by GeekCornerGH** [ItzDerock/discord-html-transcripts#91]
For now, the packages generate a "pen" icon instead of a "pin" icon when a message is pinned. Would it be possible to use a pin icon instead?

**Comment by GeekCornerGH** [comment]
Merged in upstream (https://github.com/skyra-project/discord-components/pull/317), let's try to implement this in this project now

**Comment by ItzDerock** [comment]
👍 Will work on pulling those changes into my [discord-components](https://github.com/ItzDerock/discord-components) fork.
Once I resolve any conflicts and fix a few other bugs, I'll publish a new version.

**Comment by ItzDerock** [comment]
Released in [`3.1.3`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/v3.1.3)
