### ISSUE TITLE
[Features request] Add to show pinged role & time

### ISSUE THREAD

**Issue by Cral-Cactus** [ItzDerock/discord-html-transcripts#93]
Hello, please make it to show when you ping role with <&id> and time with <t:....>

**Comment by Cral-Cactus** [comment]
Btw pinning message on transcript is broken [Image](https://i.imgur.com/QKIJ2xW.png)

**Comment by CayeOficial** [comment]
Seems that you're using an outdated version of the library because both roles and timestamps are showing and fully working.

Pinned messages are showing too, just that it has a little problem with the icon.
https://cdn.cayeoficial.com/opera_0zhZmsarkp.png
