### ISSUE TITLE
Wrong Characters 

### ISSUE THREAD

**Issue by AhmedMondo** [ItzDerock/discord-html-transcripts#96]
Hi, i have problem in  non-english chars and emojis..

here is a pic
![image](https://user-images.githubusercontent.com/55901601/205181707-99e3ccb9-94b2-4c73-91bf-260956354239.png)

and here is full sample 
https://ticket-manager.xyz/tickets/621372251215888394/kt01853310e460t9q-1543jipv8cr99000.html

and i tried adding charset = utf-8 in ngix.conf and it still not working too

**Comment by ItzDerock** [comment]
What characters/emojis specifically are causing this issue?

**Comment by AhmedMondo** [comment]
Arabic characters 
Normal emojis 

btw its not tyeped as UTF-8 i think

**Comment by SerenModz21** [comment]
I didn't have this issue until I uploaded the HTML file to my S3 bucket. however, I fixed it by adding the UTF-8 charset metatag and re-uploading the file.

before:
![before]( https://cdn.serenmodz.rocks/tnSgtvz.png)

after:
![after](https://cdn.serenmodz.rocks/purjkoz.png)

fix:
```html
<meta charset="utf-8">
```
![fix](https://cdn.serenmodz.rocks/enDrzUX.png)

**Comment by AhmedMondo** [comment]
which file

**Comment by AhmedMondo** [comment]
i think i fixed it

**Comment by AhmedMondo** [comment]
nope i didnt

**Comment by AhmedMondo** [comment]
and yup i did it

**Comment by ItzDerock** [comment]
Released in [`3.1.3`](https://github.com/ItzDerock/discord-html-transcripts/releases/tag/v3.1.3)
